dummy_challenges = [
    {"id": 1, "name": "Admin Panel", "category": "Web", "value": 500, "solved": False,
     "description": "The admin panel has a known session vulnerability. Recover the secret key to forge a cookie.",
     "connection_info": "admin-panel.ctf.local:443",
     "files": ["handout.zip"], "hints": 2, "solves": 0},
    {"id": 2, "name": "RSA Oracle", "category": "Crypto", "value": 400, "solved": True,
     "description": "A remote oracle leaks partial plaintext. Recover the full message.",
     "connection_info": "", "files": ["oracle.py", "output.txt"],
     "hints": 1, "solves": 17},
    {"id": 3, "name": "Buffer Overflow", "category": "Pwn", "value": 350, "solved": False,
     "description": "A simple stack buffer overflow. Overwrite the return address to call win().",
     "connection_info": "pwn.ctf.local:1337",
     "files": ["bof", "libc.so.6"], "hints": 0, "solves": 5},
    {"id": 4, "name": "Flag Checker", "category": "Rev", "value": 300, "solved": False,
     "description": "Reverse engineer the flag checker binary to extract the hidden flag.",
     "connection_info": "", "files": ["checker.elf"],
     "hints": 3, "solves": 2},
    {"id": 5, "name": "SQL Injection", "category": "Web", "value": 450, "solved": False,
     "description": "Bypass the login form using a SQL injection vulnerability.",
     "connection_info": "sqli.ctf.local:8080",
     "files": [], "hints": 1, "solves": 8},
    {"id": 6, "name": "Forensic Evidence", "category": "Forensics", "value": 200, "solved": False,
     "description": "Analyze the memory dump to find the attacker's exfiltration method.",
     "connection_info": "", "files": ["memdump.raw"],
     "hints": 2, "solves": 12},
    {"id": 7, "name": "JWT Forger", "category": "Crypto", "value": 375, "solved": False,
     "description": "The server uses a weak JWT secret. Crack it and forge an admin token.",
     "connection_info": "jwt.ctf.local:3000",
     "files": ["jwt_token.txt"], "hints": 0, "solves": 4},
]

dummy_scoreboard = [
    {"pos": 1, "name": "hackers_r_us", "score": 2750},
    {"pos": 2, "name": "pwn3rs", "score": 2400},
    {"pos": 3, "name": "nexus", "score": 1850},
    {"pos": 4, "name": "crypto_kids", "score": 1600},
    {"pos": 5, "name": "forensics_ftw", "score": 1200},
    {"pos": 6, "name": "rev_eng", "score": 900},
    {"pos": 7, "name": "web_wizards", "score": 600},
    {"pos": 8, "name": "noobs", "score": 200},
]
